function authPageMarkup(){
 return '<section id="auth" class="view"><div class="auth-shell"><div class="auth-brand"><img src="./assets/brand/mon-lockup.svg" alt="MON 門 Japanese OS"><span>Conta MON</span></div><div class="auth-card"><span class="eyebrow">Acesso · 入門</span><h1>Entre no seu caminho.</h1><p>Use sua conta MON para sincronizar progresso entre dispositivos.</p><label><span>E-mail</span><input id="authEmail" type="email" autocomplete="email" placeholder="voce@exemplo.com"></label><label><span>Senha</span><input id="authPassword" type="password" autocomplete="current-password" minlength="8" placeholder="mínimo 8 caracteres"></label><div class="auth-actions"><button class="auth-primary" onclick="signInMonCloud()">entrar</button><button class="auth-secondary" onclick="signUpMonCloud()">criar conta</button></div><div id="authStatus" class="auth-status" role="status" aria-live="polite"></div><small>Ao criar uma conta, seu progresso local continua preservado e pode ser sincronizado após o acesso.</small><nav class="auth-legal" aria-label="Documentos legais"><a href="legal/privacy.html" target="_blank" rel="noopener">Política de Privacidade</a><a href="legal/terms.html" target="_blank" rel="noopener">Termos de Uso</a></nav><small class="auth-minor-note">Se você é criança ou adolescente, use o MON com orientação de um responsável. Para criar a conta, o MON não pede data de nascimento, escola, endereço ou localização.</small><small class="auth-legal-note">Documentos em revisão pré-lançamento.</small></div></div></section>';
}
function ensureAuthPage(){let view=document.getElementById('auth');if(view)return view;document.querySelector('.content')?.insertAdjacentHTML('afterbegin',authPageMarkup());return document.getElementById('auth')}
function setAuthStatus(message=''){const el=document.getElementById('authStatus');if(el)el.textContent=message}
async function renderAuthPage(){
 ensureAuthPage();setAuthStatus('');
 try{const session=await monCloudSession();if(session){await go('home',{replace:true});return}}catch{}
}
