// MON Foundation Zero runtime · loaded on demand
function foundationSpeak(text){if(typeof window.speak==='function')return window.speak(text);if(!('speechSynthesis' in window)){if(typeof toast==='function')toast('Áudio indisponível neste navegador');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.82;speechSynthesis.speak(u)}
const conjugationData={
 verbs:[
  {head:'食べる',label:'Grupo 2 · ichidan',forms:{'dicionário':'食べる','polida':'食べます','negativa':'食べない','passada':'食べた','forma て':'食べて','potencial':'食べられる'},note:'Grupo 2: retire る e acrescente a terminação. É o padrão mais transparente, mas nem todo verbo terminado em る pertence a este grupo.'},
  {head:'行く',label:'Grupo 1 · godan',forms:{'dicionário':'行く','polida':'行きます','negativa':'行かない','passada':'行った','forma て':'行って','potencial':'行ける'},note:'Grupo 1: a última mora muda de coluna. 行く tem uma forma て/passada especial: 行って / 行った.'},
  {head:'話す',label:'Grupo 1 · godan',forms:{'dicionário':'話す','polida':'話します','negativa':'話さない','passada':'話した','forma て':'話して','potencial':'話せる'},note:'Final す: します / さない / した / して / せる. Observe a família inteira como transformação sonora.'},
  {head:'読む',label:'Grupo 1 · godan',forms:{'dicionário':'読む','polida':'読みます','negativa':'読まない','passada':'読んだ','forma て':'読んで','potencial':'読める'},note:'Finais む/ぶ/ぬ compartilham んで / んだ na forma て e no passado.'},
  {head:'買う',label:'Grupo 1 · godan',forms:{'dicionário':'買う','polida':'買います','negativa':'買わない','passada':'買った','forma て':'買って','potencial':'買える'},note:'Com verbos terminados em う, a negativa usa わ: 買わない.'},
  {head:'する',label:'Irregular',forms:{'dicionário':'する','polida':'します','negativa':'しない','passada':'した','forma て':'して','potencial':'できる'},note:'する é irregular e extremamente produtivo: substantivo + する cria muitos verbos, como 勉強する.'},
  {head:'来る',label:'Irregular',forms:{'dicionário':'来る','polida':'来ます','negativa':'来ない','passada':'来た','forma て':'来て','potencial':'来られる'},note:'来る muda leitura entre formas. Aprenda a família como um bloco de alta frequência.'}
 ],
 adjectives:[
  {head:'高い',label:'adjetivo い',forms:{'não-passado':'高いです','negativa':'高くないです','passada':'高かったです','neg. passada':'高くなかったです','antes de N':'高い店','advérbio':'高く'},note:'Adjetivos い conjugam no próprio adjetivo. Não use でした diretamente após 高い.'},
  {head:'静か',label:'adjetivo な',forms:{'não-passado':'静かです','negativa':'静かじゃないです','passada':'静かでした','neg. passada':'静かじゃなかったです','antes de N':'静かな店','advérbio':'静かに'},note:'Adjetivos な usam な antes de substantivo, mas não antes de です.'},
  {head:'好き',label:'adjetivo な',forms:{'não-passado':'好きです','negativa':'好きじゃないです','passada':'好きでした','neg. passada':'好きじゃなかったです','antes de N':'好きな店','alvo típico':'日本語が好きです'},note:'好き funciona gramaticalmente como adjetivo な. O alvo do gosto costuma aparecer com が.'}
 ]
};
let conjKind='verbs',conjIndex=0;
function selectConjugation(i){conjIndex=Number(i)||0;renderConjugation()}\nfunction renderConjugation(){const rows=conjugationData[conjKind];if(!rows)return;document.querySelectorAll('[data-conj-kind]').forEach(b=>b.classList.toggle('active',b.dataset.conjKind===conjKind));document.getElementById('conjList').innerHTML=rows.map((x,i)=>`<button class="${i===conjIndex?'active':''}" data-mon-command="selectConjugation(${i})"><b>${x.head}</b><small>${x.label}</small></button>`).join('');const x=rows[Math.min(conjIndex,rows.length-1)];document.getElementById('conjTable').innerHTML=Object.entries(x.forms).map(([k,v])=>`<div class="conj-cell"><span>${k}</span><b>${v}</b><button class="audio-btn" style="margin-top:7px" data-mon-command="foundationSpeak('${v.replaceAll("'","\\'")}')">▶</button></div>`).join('');document.getElementById('conjNote').textContent=x.note}

const soundPairs=[
 {a:'おばさん',b:'おばあさん',aPt:'tia / senhora',bPt:'avó',cue:'A vogal longa ocupa tempo extra.'},
 {a:'きて',b:'きって',aPt:'venha / vestindo (contexto)',bPt:'selo postal',cue:'O pequeno っ cria uma mora de fechamento.'},
 {a:'ここ',b:'こうこう',aPt:'aqui',bPt:'ensino médio',cue:'A duração de お muda o ritmo e a palavra.'},
 {a:'びよういん',b:'びょういん',aPt:'salão de beleza',bPt:'hospital',cue:'Yōon + duração merecem escuta lenta.'}
];
let currentSoundQuiz=null;
function playSoundQuiz(){const pair=soundPairs[Math.floor(Math.random()*soundPairs.length)];const target=Math.random()<.5?'a':'b';currentSoundQuiz={pair,target};foundationSpeak(pair[target]);const wrap=document.getElementById('soundQuizOptions');wrap.innerHTML=`<button data-mon-command="answerSoundQuiz('a')">${pair.a}</button><button data-mon-command="answerSoundQuiz('b')">${pair.b}</button>`;document.getElementById('soundQuizFeedback').textContent='Qual forma você ouviu? Não leia tradução ainda.'}
function answerSoundQuiz(choice){if(!currentSoundQuiz)return;const {pair,target}=currentSoundQuiz,ok=choice===target;const btns=[...document.querySelectorAll('#soundQuizOptions button')];btns.forEach((b,i)=>{const key=i===0?'a':'b';b.disabled=true;if(key===target)b.classList.add('correct');if(key===choice&&!ok)b.classList.add('wrong')});if(ok){state.soundWins=(state.soundWins||0)+1;state.xp+=2;save()}document.getElementById('soundQuizFeedback').textContent=`${ok?'Certo.':'Compare de novo.'} ${pair.a} = ${pair.aPt}; ${pair.b} = ${pair.bPt}. ${pair.cue}`}

const confusionPairs=[
 {a:'シ',b:'ツ',cue:'シ tende a subir pela direita; ツ cai de cima para baixo.'},
 {a:'ソ',b:'ン',cue:'Observe a direção dos dois traços curtos antes do traço longo.'},
 {a:'ぬ',b:'め',cue:'ぬ fecha com um laço; め não termina com o mesmo gancho.'},
 {a:'れ',b:'ね',cue:'ね ganha um laço/volta final; れ permanece mais aberto.'},
 {a:'さ',b:'き',cue:'き cruza com um traço adicional; さ é mais econômico.'},
 {a:'ク',b:'ケ',cue:'ケ adiciona um traço vertical e ganha estrutura mais aberta.'},
 {a:'ウ',b:'ワ',cue:'ウ possui o pequeno traço superior; ワ abre a lateral.'},
 {a:'ル',b:'レ',cue:'ル termina em duas pernas; レ é um único gesto principal.'}
];
let confusionIndex=0,confusionTarget='a';
function renderConfusions(){const wrap=document.getElementById('confusionGrid');if(!wrap)return;wrap.innerHTML=confusionPairs.map((x,i)=>`<button class="confusion-card ${i===confusionIndex?'active':''}" data-mon-command="practiceConfusion(${i})"><b>${x.a} ${x.b}</b><span>${x.cue}</span></button>`).join('');newConfusionQuestion()}
function practiceConfusion(i){confusionIndex=i;renderConfusions()}
function newConfusionQuestion(){const p=confusionPairs[confusionIndex];if(!p)return;confusionTarget=Math.random()<.5?'a':'b';document.getElementById('confusionPrompt').textContent=p[confusionTarget];document.getElementById('confusionChoices').innerHTML=`<button data-mon-command="answerConfusion('a')">${p.a}</button><button data-mon-command="answerConfusion('b')">${p.b}</button>`;document.getElementById('confusionFeedback').textContent='Identifique sem usar romaji.'}
function answerConfusion(key){const p=confusionPairs[confusionIndex],ok=key===confusionTarget;document.getElementById('confusionFeedback').textContent=(ok?'Correto. ':'Revise o contraste. ')+p.cue;if(ok){state.xp+=1;save()}setTimeout(newConfusionQuestion,650)}

const sentencePuzzles=[
 {pt:'Eu compro água no konbini.',tokens:['わたしは','コンビニで','みずを','かいます。'],answer:['わたしは','コンビニで','みずを','かいます。'],note:'は tópico · で lugar da ação · を objeto · verbo no fim.'},
 {pt:'Vou à estação às sete.',tokens:['しちじに','えきへ','いきます。'],answer:['しちじに','えきへ','いきます。'],note:'に marca horário; へ marca direção.'},
 {pt:'Há uma loja em frente à estação.',tokens:['えきのまえに','みせが','あります。'],answer:['えきのまえに','みせが','あります。'],note:'Lugar + に, entidade + が, existência no fim.'},
 {pt:'Como sushi com um amigo.',tokens:['ともだちと','すしを','たべます。'],answer:['ともだちと','すしを','たべます。'],note:'と companhia; を objeto; verbo fecha.'},
 {pt:'Esta loja é barata.',tokens:['このみせは','やすいです。'],answer:['このみせは','やすいです。'],note:'Adjetivo い pode funcionar como predicado.'},
 {pt:'Como estou ocupado, não vou.',tokens:['いそがしいから、','いきません。'],answer:['いそがしいから、','いきません。'],note:'から conecta motivo → consequência.'}
];
let sentencePuzzleIndex=0,sentenceBuilt=[];
function shuffleArray(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function renderSentencePuzzle(){const x=sentencePuzzles[sentencePuzzleIndex];if(!x)return;document.getElementById('sentencePrompt').textContent=x.pt;const pool=shuffleArray(x.tokens.map((t,i)=>({t,i})));document.getElementById('sentenceBank').innerHTML=pool.map(o=>`<button class="sentence-token" data-token-index="${o.i}" data-mon-command="addSentenceToken(${o.i},this)">${o.t}</button>`).join('');sentenceBuilt=[];renderSentenceBuilt();document.getElementById('sentenceFeedback').className='sentence-feedback';document.getElementById('sentenceFeedback').textContent='Monte os blocos. Partículas mostram o papel de cada um.'}
function renderSentenceBuilt(){const wrap=document.getElementById('sentenceBuild');if(!sentenceBuilt.length){wrap.innerHTML='<span style="color:#647181;font-size:8px">sua frase aparece aqui</span>';return}wrap.innerHTML=sentenceBuilt.map((i,pos)=>`<button class="sentence-token" data-mon-command="removeSentenceToken(${pos})">${sentencePuzzles[sentencePuzzleIndex].tokens[i]}</button>`).join('')}
function addSentenceToken(i,btn){if(sentenceBuilt.includes(i))return;sentenceBuilt.push(i);btn.classList.add('used');renderSentenceBuilt()}
function removeSentenceToken(pos){const idx=sentenceBuilt.splice(pos,1)[0];document.querySelectorAll(`[data-token-index="${idx}"]`).forEach(b=>b.classList.remove('used'));renderSentenceBuilt()}
function resetSentencePuzzle(){renderSentencePuzzle()}
function nextSentencePuzzle(){sentencePuzzleIndex=(sentencePuzzleIndex+1)%sentencePuzzles.length;renderSentencePuzzle()}
function checkSentencePuzzle(){const x=sentencePuzzles[sentencePuzzleIndex];const built=sentenceBuilt.map(i=>x.tokens[i]);const ok=JSON.stringify(built)===JSON.stringify(x.answer);const f=document.getElementById('sentenceFeedback');f.className='sentence-feedback '+(ok?'good':'bad');f.textContent=(ok?'Boa estrutura. ':'Ainda não. Modelo: '+x.answer.join(' ')+'. ')+x.note;if(ok){state.sentenceSolved=(state.sentenceSolved||0)+1;state.xp+=4;save()}}
function speakSentenceAnswer(){speak(sentencePuzzles[sentencePuzzleIndex].answer.join(' '))}

let grammarCategory='ALL';
function grammarCategoryOf(x){const f=(x.function+' '+x.form).toLowerCase();if(/[はがをにでへとも]/.test(x.form)&&x.level==='ZERO')return 'Partículas';if(/verbo|ação|forma|pedido|permiss|proibi|potencial|passiv|causativ|hábito|plano|intenção|experimenta|preparar/.test(f))return 'Verbos';if(/adjet|descre|aparência|semelhança|grau|tendência/.test(f))return 'Descrição';if(/porque|motivo|condi|mesmo se|apesar|durante|enquanto|cada vez|à medida|conector|objetivo|causa/.test(f))return 'Conexões';if(x.level==='N3'||/opinião|inferência|expectativa|nuance|explicar|regra|decisão|ênfase|conclusão/.test(f))return 'Nuance';return 'Fundamentos'}
function renderGrammarMap(){const wrap=document.getElementById('grammarMap');if(!wrap)return;const cats=['Fundamentos','Partículas','Verbos','Descrição','Conexões','Nuance'];wrap.innerHTML=cats.map(c=>`<div><b>${c}</b><span>${grammarData.filter(x=>grammarCategoryOf(x)===c).length} padrões</span></div>`).join('')}
function grammarBridge(x){const f=x.form;if(f.includes('は'))return 'Não traduza は como uma palavra fixa. Ele organiza o tópico; em uso de partícula lê-se wa.';if(f.includes('が'))return 'Português/inglês tendem a depender mais da posição. Japonês usa が para marcar sujeito/foco em muitos contextos.';if(f.includes('を'))return 'を marca o objeto e normalmente é pronunciado o na fala moderna.';if(f.includes('に')||f.includes('で'))return 'Evite procurar uma única preposição equivalente: escolha a partícula pela função do bloco.';if(/V|ます|て|辞書形/.test(f))return 'O verbo japonês carrega muita informação no final da frase. Espere o predicado antes de fechar a interpretação.';if(/adj|い|な/.test(f))return 'Adjetivos japoneses não concordam em gênero ou número como no português; い e な têm comportamentos próprios.';return 'Procure a função comunicativa primeiro e só depois compare com uma tradução em português/inglês.'}
function openGrammarDrawer(i){const x=grammarData[i];if(!x)return;state.grammarOpened[i]=Date.now();save();const c=document.getElementById('grammarDrawerContent');c.innerHTML=`<span class="eyebrow">${x.level} · ${grammarCategoryOf(x)}</span><h2>${x.function}</h2><p style="font-size:10px;color:#98a3af;line-height:1.7">${x.meaning}</p><div class="grammar-drawer-form">${x.form}</div><div class="grammar-drawer-section"><b>EXEMPLO VIVO</b><div class="grammar-drawer-example">${x.jp}</div><p>${x.pt}</p><button class="secondary" data-mon-command="foundationSpeak('${x.jp.replaceAll("'","\\'")}')">▶ ouvir exemplo</button></div><div class="grammar-drawer-section"><b>PONTE PT / EN</b><p>${grammarBridge(x)}</p></div><div class="grammar-drawer-section"><b>NOTA DE USO</b><p>${x.note||'Aprenda o padrão dentro de frases completas e varie apenas um elemento por vez antes de produzir livremente.'}</p></div><div class="grammar-drawer-section"><b>RECUPERAÇÃO</b><p>Sem olhar a forma acima: como você expressaria “${x.pt}” em japonês?</p><button class="ghost" data-mon-command="showGrammarSelfCheck()">revelar modelo</button><div id="grammarSelfCheck" class="grammar-selfcheck">${x.jp}<br><span>${x.form}</span></div></div>`;document.getElementById('grammarDrawer').classList.add('open')}
function showGrammarSelfCheck(){const e=document.getElementById('grammarSelfCheck');if(e)e.style.display='block'}\nfunction closeGrammarDrawer(){document.getElementById('grammarDrawer').classList.remove('open')}
function setGrammarCategory(cat){grammarCategory=cat;document.querySelectorAll('[data-grammar-cat]').forEach(b=>b.classList.toggle('active',b.dataset.grammarCat===cat));renderGrammar(grammarLevel,document.getElementById('grammarSearch')?.value||'')}

let foundationKanaScript='hira',foundationKanaSet='basic',kanaQuizDirection='read',currentKanaQuiz=null,grammarLevel='ZERO';
function allKanaItems(script=foundationKanaScript,set=foundationKanaSet){return kanaCourse[script][set]||[]}
function isKanaDue(k){return reviewIsDue('kana',k,true)}
function countKanaInTraining(){return Object.keys(state.kanaMastery||{}).filter(k=>kanaMastery(k)>0&&kanaMastery(k)<5&&isKanaDue(k)).length}
function kanaMastery(k){return Math.max(0,Math.min(5,Number(state.kanaMastery?.[k]??reviewMastery('kana',k))))}
function gradeKana(k,g,quiet=false){const prev=kanaMastery(k);state.kanaMastery[k]=g==='hard'?Math.max(0,prev-1):g==='good'?Math.min(5,prev+1):Math.min(5,prev+2);const r=gradeReview('kana',k,g);state.kanaReviews[k]={...r};if(!quiet)state.xp+=g==='hard'?1:g==='good'?3:5;save();renderFoundationKana();if(!quiet)toast(`Kana ${k} · próxima volta ${g==='hard'?'em algumas horas':Math.max(1,Math.round(r.interval))+'d'}`)}
function renderFoundationProgress(){const day=Math.max(1,Math.min(FOUNDATION_TOTAL,state.foundationDay||1)),pct=state.foundationComplete?100:Math.round((day-1)/FOUNDATION_TOTAL*100);[['foundationPct',pct+'%'],['zeroEntryPct',pct+'%']].forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v});const f=document.getElementById('foundationProgressFill');if(f)f.style.width=pct+'%';const n=document.getElementById('foundationNow');if(n){const u=foundationUnits[day-1];n.textContent=state.foundationComplete?'Fundação concluída · N5 liberado':`Sessão ${day} · ${u.title}`};const firm=Object.values(state.kanaMastery||{}).filter(v=>v>=3).length;const due=Object.keys(state.kanaMastery||{}).filter(k=>kanaMastery(k)>0&&isKanaDue(k)).length;const rom=state.romajiMode==='show'?100:state.romajiMode==='hide'?0:Math.max(0,Math.round(100-(day-1)/(FOUNDATION_TOTAL-1)*100));const opened=new Set([...Object.keys(state.grammarOpened||{}),...Object.keys(state.grammarRecall||{})]).size;const vals=[['kanaKnownMetric',firm],['kanaDueMetric',due],['romajiMetric',rom+'%'],['grammarSeenMetric',opened]];vals.forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v});const rb=document.getElementById('romajiModeBtn');if(rb)rb.textContent=state.romajiMode==='show'?'mostrar':state.romajiMode==='hide'?'oculto':'automático'}
function renderFoundationRunway(){const wrap=document.getElementById('foundationRunway');if(!wrap)return;const d=state.foundationDay||1;wrap.innerHTML=foundationUnits.map(u=>{const done=state.foundationComplete||u.n<d,current=!state.foundationComplete&&u.n===d,locked=!state.foundationComplete&&u.n>d;return `<button class="foundation-step ${done?'done':''} ${current?'current':''} ${locked?'locked':''}" data-mon-command="openFoundationUnit(${u.n})"><small>sessão ${u.n}/${FOUNDATION_TOTAL}</small><b>${u.title}</b><p>${u.desc}</p><i>${u.symbol}</i></button>`}).join('')}
function renderPronunciation(){const wrap=document.getElementById('soundGrid');if(!wrap)return;wrap.innerHTML=pronunciationData.map(x=>`<article class="sound-card"><header><span class="sound-symbol">${x.symbol}</span><button data-mon-command="foundationSpeak('${x.audio.replaceAll("'","\\'")}')" aria-label="Ouvir ${x.title}">▶</button></header><b>${x.title}</b><p>${x.text}</p><span class="bridge">${x.bridge}</span></article>`).join('')}
function toggleRomajiMode(){state.romajiMode=state.romajiMode==='auto'?'show':state.romajiMode==='show'?'hide':'auto';save();renderFoundationKana();renderFoundationProgress()}
function renderFoundationKana(){const wrap=document.getElementById('foundationKanaGrid');if(!wrap)return;const items=allKanaItems();wrap.innerHTML=items.map(([k,r])=>`<button class="foundation-kana m${kanaMastery(k)} ${currentKanaQuiz?.kana===k?'selected':''} ${isKanaDue(k)&&kanaMastery(k)>0?'due':'scheduled'}" data-mon-command="previewFoundationKana('${k}','${r}')"><b>${renderJapaneseReading(k,k,{romaji:r})}</b></button>`).join('')}
function previewFoundationKana(k,r){foundationSpeak(k);currentKanaQuiz={kana:k,roman:r};document.getElementById('kanaQuizPrompt').textContent=k;document.getElementById('kanaQuizFeedback').textContent=k+' · '+r+'. Ouça e repita.'}\nfunction setKanaQuizDirection(dir){kanaQuizDirection=dir;newKanaQuiz()}
function speakCurrentKana(){if(currentKanaQuiz)speak(currentKanaQuiz.kana)}
function newKanaQuiz(){const items=allKanaItems();if(!items.length)return;const sorted=[...items].sort((a,b)=>(isKanaDue(a[0])?0:1)-(isKanaDue(b[0])?0:1)||kanaMastery(a[0])-kanaMastery(b[0])||Math.random()-.5);const item=sorted[Math.floor(Math.random()*Math.min(8,sorted.length))]||sorted[0];currentKanaQuiz={kana:item[0],roman:item[1]};const prompt=document.getElementById('kanaQuizPrompt'),title=document.getElementById('kanaQuizTitle'),opts=document.getElementById('kanaQuizOptions'),fb=document.getElementById('kanaQuizFeedback');if(!prompt||!opts)return;const pool=items.map(x=>kanaQuizDirection==='read'?x[1]:x[0]);const answer=kanaQuizDirection==='read'?item[1]:item[0];prompt.textContent=kanaQuizDirection==='read'?item[0]:item[1];title.textContent=kanaQuizDirection==='read'?'Leia sem romaji.':'Recupere a forma.';const options=shuffledOptions(answer,pool);opts.innerHTML=options.map((o,i)=>`<button data-kana-option="${i}" data-mon-command="answerKanaQuiz(${i})">${o}</button>`).join('');currentKanaQuiz.options=options;currentKanaQuiz.answer=answer;if(fb)fb.textContent=kanaQuizDirection==='read'?'Escolha o som. Depois ouça e repita.':'Escolha o kana sem consultar o mapa.';renderFoundationKana()}
function answerKanaQuiz(i){if(!currentKanaQuiz)return;const buttons=[...document.querySelectorAll('[data-kana-option]')];if(buttons.some(b=>b.disabled))return;const chosen=currentKanaQuiz.options[i],ok=chosen===currentKanaQuiz.answer;buttons.forEach((b,j)=>{b.disabled=true;if(currentKanaQuiz.options[j]===currentKanaQuiz.answer)b.classList.add('correct')});if(!ok)buttons[i].classList.add('wrong');gradeKana(currentKanaQuiz.kana,ok?'good':'hard',true);const fb=document.getElementById('kanaQuizFeedback');fb.innerHTML=`${ok?'Boa.':'Corrija agora.'} <b>${currentKanaQuiz.kana} · ${currentKanaQuiz.roman}</b> <button class="small-btn" data-mon-command="newKanaQuiz()">próximo →</button>`;speak(currentKanaQuiz.kana)}
function renderGrammar(level=grammarLevel,query=''){grammarLevel=level;document.querySelectorAll('[data-grammar-level]').forEach(b=>b.classList.toggle('active',b.dataset.grammarLevel===level));const q=(query||'').trim().toLowerCase();const rows=grammarData.map((x,i)=>({x,i})).filter(o=>(level==='ALL'||o.x.level===level)&&(grammarCategory==='ALL'||grammarCategoryOf(o.x)===grammarCategory)&&(!q||[o.x.function,o.x.form,o.x.meaning,o.x.jp,o.x.pt,o.x.note,grammarCategoryOf(o.x)].join(' ').toLowerCase().includes(q)));const wrap=document.getElementById('grammarGrid');if(!wrap)return;wrap.innerHTML=rows.map(({x,i})=>`<article class="grammar-card" data-mon-command="openGrammarDrawer(${i})"><span class="g-level">${x.level} · ${grammarCategoryOf(x)}</span><button data-mon-command="event.stopPropagation();speak('${x.jp.replaceAll("'","\'")}')" aria-label="Ouvir exemplo">▶</button><h4>${x.function}</h4><div class="g-form">${x.form}</div><p>${x.meaning}${x.note?` ${x.note}`:''}</p><div class="g-example"><b>${x.jp}</b><span>${x.pt}</span></div></article>`).join('')||'<div class="session-feedback">Nenhum padrão encontrado com este filtro.</div>'}

function renderFoundationReferenceAtlas(){
 const host=document.getElementById('foundationReferenceAtlas');if(!host)return;
 const kanaGrid=items=>items.map(([k,r])=>`<span><b>${renderJapaneseReading(k,k,{romaji:r})}</b></span>`).join('');
 const particles=['は','が','を','に','で','へ','と','の','も','か'];
 const grammar=particles.map(p=>grammarData.find(x=>x.form===p||x.form?.startsWith(p))||null).filter(Boolean);
 host.innerHTML=`<div class="reference-atlas-head"><div><span class="eyebrow">Atlas de referência · 参照</span><h3>Veja o sistema inteiro antes de praticar.</h3><p>Abra qualquer mapa quando precisar se orientar. O treino continua por pequenos blocos; o atlas mostra onde cada peça mora.</p></div><span class="reference-atlas-mark">全</span></div>
 <div class="reference-atlas-grid">
  <details open><summary><span>01</span><b>Hiragana · 46 formas</b><em>ひらがな</em></summary><div class="reference-kana-grid">${kanaGrid(kanaCourse.hira.basic)}</div><p>Dakuten e combinações aparecem depois, sobre esta mesma malha.</p></details>
  <details><summary><span>02</span><b>Katakana · 46 formas</b><em>カタカナ</em></summary><div class="reference-kana-grid">${kanaGrid(kanaCourse.kata.basic)}</div><p>Mesmos sons básicos, outra escrita. Observe シ/ツ e ソ/ン deliberadamente.</p></details>
  <details><summary><span>03</span><b>Gramática-base</b><em>文法</em></summary><div class="reference-function-grid">
   <span><b>は</b><small>tópico</small></span><span><b>が</b><small>foco / sujeito</small></span><span><b>を</b><small>objeto</small></span><span><b>に</b><small>ponto / destino</small></span><span><b>で</b><small>palco da ação</small></span><span><b>へ</b><small>direção</small></span><span><b>の</b><small>relação</small></span><span><b>と</b><small>companhia / citação</small></span><span><b>も</b><small>também</small></span><span><b>か</b><small>pergunta</small></span>
  </div><p>Escolha partículas pela função do bloco, não por uma tradução fixa em português.</p></details>
  <details><summary><span>04</span><b>Formas verbais essenciais</b><em>活用</em></summary><div class="reference-verbs"><span><b>Vます</b><small>polido / não-passado</small></span><span><b>Vません</b><small>negativo</small></span><span><b>Vました</b><small>passado</small></span><span><b>Vて</b><small>conectar / pedir</small></span></div><p>O predicado fecha a oração; mudar sua forma altera tempo, polaridade ou conexão.</p></details>
  <details><summary><span>05</span><b>Números & contadores</b><em>数</em></summary><div class="reference-verbs"><span><b>〜時</b><small>horas</small></span><span><b>〜人</b><small>pessoas</small></span><span><b>〜円</b><small>ienes</small></span><span><b>〜つ</b><small>contador geral</small></span></div><p>Contar em japonês depende da categoria. A Fundação ensina os padrões que aparecem primeiro em tarefas reais.</p></details>
 </div>`;
}

function renderFoundation(){renderFoundationProgress();renderFoundationRunway();renderFoundationReferenceAtlas();renderPronunciation();renderFoundationKana();renderGrammarMap();renderConjugation();renderGrammar(grammarLevel,document.getElementById('grammarSearch')?.value||'');renderConfusions();renderSentencePuzzle();if(!currentKanaQuiz)newKanaQuiz();if(!currentSoundQuiz)playSoundQuiz()}

let __foundationControlsBound=false;
function bindFoundationControls(){
 if(__foundationControlsBound)return;__foundationControlsBound=true;
 document.querySelectorAll('[data-conj-kind]').forEach(b=>b.addEventListener('click',()=>{conjKind=b.dataset.conjKind;conjIndex=0;renderConjugation()}));
 document.querySelectorAll('[data-foundation-script]').forEach(b=>b.addEventListener('click',()=>{foundationKanaScript=b.dataset.foundationScript;document.querySelectorAll('[data-foundation-script]').forEach(x=>x.classList.toggle('active',x===b));renderFoundationKana();newKanaQuiz()}));
 document.querySelectorAll('[data-foundation-set]').forEach(b=>b.addEventListener('click',()=>{foundationKanaSet=b.dataset.foundationSet;document.querySelectorAll('[data-foundation-set]').forEach(x=>x.classList.toggle('active',x===b));renderFoundationKana();newKanaQuiz()}));
 document.querySelectorAll('[data-grammar-level]').forEach(b=>b.addEventListener('click',()=>renderGrammar(b.dataset.grammarLevel,document.getElementById('grammarSearch')?.value||'')));
 document.querySelectorAll('[data-grammar-cat]').forEach(b=>b.addEventListener('click',()=>setGrammarCategory(b.dataset.grammarCat)));
 document.getElementById('grammarSearch')?.addEventListener('input',e=>renderGrammar(grammarLevel,e.target.value));
}
bindFoundationControls();
