// MON Kanji Atlas runtime · loaded on demand
function themeLabel(t){return t==='survival'?'sobrevivência':t==='city'?'cidade':'dia a dia'}
function renderKanjiList(filter='all',query=''){
 const q=query.trim().toLowerCase(); const wrap=document.getElementById('kanjiList');wrap.innerHTML='';
 kanjiData.forEach((x,i)=>{if(filter!=='all'&&x.theme!==filter)return;const hay=[x.k,x.m,...x.on,...x.kun,...x.ex.flat()].join(' ').toLowerCase();if(q&&!hay.includes(q))return;const b=document.createElement('button');b.className='kanji-chip'+(i===currentKanji?' active':'')+(isDue(x.k)?' due':'');b.textContent=x.k;b.title=x.m;b.onclick=()=>selectKanji(i);wrap.appendChild(b)});
}
function selectKanji(i){currentKanji=i;const x=kanjiData[i];document.getElementById('kanjiGlyph').textContent=x.k;document.getElementById('ghostKanji').textContent=x.k;document.getElementById('strokeCount').textContent=x.strokes+' traços';document.getElementById('kanjiTheme').textContent=themeLabel(x.theme);document.getElementById('kanjiMeaning').textContent=x.m;document.getElementById('kanjiNote').textContent=x.note;document.getElementById('kanjiStory').textContent=x.story;document.getElementById('readings').innerHTML=[...x.on.map(r=>`<span class="reading"><small>on</small>${r}</span>`),...x.kun.map(r=>`<span class="reading"><small>kun</small>${r}</span>`)].join('');document.getElementById('kanjiExamples').innerHTML=x.ex.map(e=>`<div class="example"><div><b>${e[0]}</b><br><span>${e[1]} • ${e[2]}</span></div><button class="audio-btn" onclick="speak('${e[1].replaceAll("'","\\'")}')">▶ ouvir</button></div>`).join('');document.getElementById('dueInfo').textContent=reviewText(x.k);clearDraw(drawCtx,drawCanvas);renderKanjiList(activeFilter,document.getElementById('kanjiSearch').value);updateForge()}
function speak(text){if(!('speechSynthesis' in window)){toast('Áudio indisponível neste navegador');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.82;const jp=speechSynthesis.getVoices().find(v=>v.lang?.toLowerCase().startsWith('ja'));if(jp)u.voice=jp;speechSynthesis.speak(u)}
let activeFilter='all';document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderKanjiList(activeFilter,document.getElementById('kanjiSearch').value)}));document.getElementById('kanjiSearch').addEventListener('input',e=>renderKanjiList(activeFilter,e.target.value));
function isDue(k){return reviewIsDue('kanji',k,true)}
function reviewText(k){const r=reviewRecord('kanji',k);if(!r)return 'Ainda não revisado.';const diff=r.due-Date.now();if(diff<=0)return 'Revisão disponível agora.';const h=Math.round(diff/3600000);return h<24?`Próxima revisão em ~${Math.max(1,h)}h.`:`Próxima revisão em ~${Math.round(h/24)} dia(s).`}
function gradeKanji(k,g,quiet=false){const r=gradeReview('kanji',k,g);state.reviews[k]={...r,m:reviewMastery('kanji',k)};if(!quiet)state.xp+=g==='hard'?3:g==='good'?8:12;save();if(document.getElementById('dueInfo')&&kanjiData[currentKanji]?.k===k)document.getElementById('dueInfo').textContent=reviewText(k);renderKanjiList(activeFilter,document.getElementById('kanjiSearch')?.value||'');if(!quiet)toast('Revisão agendada • +'+(g==='hard'?3:g==='good'?8:12)+' XP')}
function grade(g){gradeKanji(kanjiData[currentKanji].k,g)}
document.querySelectorAll('.grade').forEach(b=>b.addEventListener('click',()=>grade(b.dataset.grade)));

function toggleForge(){const a=document.getElementById('forgeAnswer'),b=document.getElementById('forgeBtn');const show=!a.classList.contains('revealed');a.classList.toggle('revealed',show);b.textContent=show?'ocultar e tentar de novo':'revelar resposta'}
function updateForge(){const x=kanjiData[currentKanji];const p=document.getElementById('forgePrompt'),a=document.getElementById('forgeAnswer'),b=document.getElementById('forgeBtn');if(!p)return;p.textContent=`Qual kanji significa “${x.m.toLowerCase()}”?`;a.textContent=`${x.k} · ${x.ex[0][1]}`;a.classList.remove('revealed');b.textContent='revelar resposta'}
