// MON Kanji Atlas · guided study surface, loaded on demand
let activeFilter='all',kanjiStudyStep='overview';
function themeLabel(t){return t==='survival'?'sobrevivência':t==='city'?'cidade':'dia a dia'}
function isDue(k){return reviewIsDue('kanji',k,true)}
function reviewText(k){const r=reviewRecord('kanji',k);if(!r)return 'Novo · ainda não revisado';const diff=r.due-Date.now();if(diff<=0)return 'Revisar agora';const h=Math.round(diff/3600000);return h<24?`Revisão em ~${Math.max(1,h)}h`:`Revisão em ~${Math.round(h/24)} dia(s)`}
function kanjiMastery(x){const r=reviewRecord('kanji',x.k),base=r?Math.round(reviewMastery('kanji',x.k)*100):0,lab=state.kanjiLab||{},last=lab.last?.k===x.k?lab.last:null;return{overall:Math.max(base,last?.ok?45:0),meaning:last?.mode==='meaning'&&last.ok?80:base,reading:last?.mode==='reading'&&last.ok?80:Math.round(base*.8),contrast:last?.mode==='contrast'&&last.ok?75:Math.round(base*.7),writing:Math.round(base*.55)}}
function masteryState(v){return v>=75?'forte':v>=40?'em progresso':'praticar'}
function ensureKanjiAtlas(){
 const host=document.getElementById('kanji');if(!host||host.dataset.ready)return;host.dataset.ready='1';
 host.innerHTML=`<div class="ka-shell"><header class="ka-head"><div><span class="eyebrow">Kanji Atlas · 漢字</span><h2>Um kanji. Uma próxima ação.</h2><p>O MON escolhe o próximo passo usando revisão e evidências de recuperação.</p></div><button class="ka-library-toggle" onclick="toggleKanjiLibrary()">explorar kanji</button></header><div class="ka-workspace"><main class="ka-main"><section id="kanjiFocus"></section><section id="kanjiStudyFlow"></section><section id="kanjiContext"></section></main><aside class="ka-library" id="kanjiLibrary"><div class="ka-library-head"><strong>Seus kanji</strong><small id="kanjiLibrarySummary"></small></div><input id="kanjiSearch" class="search" placeholder="Buscar kanji, leitura ou sentido…"><div class="ka-status-filters"><button class="active" data-kstatus="all">Todos</button><button data-kstatus="due">Revisar</button><button data-kstatus="learning">Aprendendo</button><button data-kstatus="mastered">Dominados</button></div><div class="filter-row"><button class="filter active" data-filter="all">Todos</button><button class="filter" data-filter="survival">Sobrevivência</button><button class="filter" data-filter="city">Cidade</button><button class="filter" data-filter="daily">Dia a dia</button></div><div id="kanjiList" class="ka-list"></div></aside></div></div>`;
 host.querySelector('#kanjiSearch').addEventListener('input',e=>renderKanjiList(activeFilter,e.target.value));
 host.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;host.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderKanjiList(activeFilter,host.querySelector('#kanjiSearch').value)}));
 host.querySelectorAll('[data-kstatus]').forEach(b=>b.addEventListener('click',()=>{host.dataset.status=b.dataset.kstatus;host.querySelectorAll('[data-kstatus]').forEach(x=>x.classList.toggle('active',x===b));renderKanjiList(activeFilter,host.querySelector('#kanjiSearch').value)}));
}
function toggleKanjiLibrary(){document.getElementById('kanjiLibrary')?.classList.toggle('open')}
function renderKanjiList(filter='all',query=''){
 ensureKanjiAtlas();const q=query.trim().toLowerCase(),wrap=document.getElementById('kanjiList'),status=document.getElementById('kanji')?.dataset.status||'all';if(!wrap)return;wrap.innerHTML='';let shown=0,due=0;
 kanjiData.forEach((x,i)=>{const mastery=kanjiMastery(x).overall,d=isDue(x.k);if(d)due++;if(filter!=='all'&&x.theme!==filter)return;if(status==='due'&&!d)return;if(status==='learning'&&(mastery<=0||mastery>=75))return;if(status==='mastered'&&mastery<75)return;const hay=[x.k,x.m,...x.on,...x.kun,...x.ex.flat()].join(' ').toLowerCase();if(q&&!hay.includes(q))return;shown++;const b=document.createElement('button');b.className='ka-kanji'+(i===currentKanji?' active':'')+(d?' due':'');b.innerHTML=`<b>${x.k}</b><span><strong>${x.m}</strong><small>${d?'revisar hoje':mastery?mastery+'% domínio':'novo'}</small></span>`;b.onclick=()=>{selectKanji(i);document.getElementById('kanjiLibrary')?.classList.remove('open')};wrap.appendChild(b)});
 const sum=document.getElementById('kanjiLibrarySummary');if(sum)sum.textContent=`${shown} visíveis · ${due} para revisar`;
}
function kanjiFocusMarkup(x){
 const m=kanjiMastery(x),first=x.ex[0];return `<div class="ka-focus"><div class="ka-glyph-card"><span class="eyebrow">${themeLabel(x.theme)} · ${x.strokes} traços</span><b class="ka-glyph">${x.k}</b><span class="ka-due">${reviewText(x.k)}</span></div><div class="ka-focus-copy"><span class="eyebrow">caractere atual</span><h1>${x.m}</h1><p>${x.note}</p><div class="ka-word"><b>${first[0]}</b><span>${first[1]} · ${first[2]}</span><button onclick="speak('${first[1].replaceAll("'","\\'")}')">▶ ouvir</button></div><button class="primary" onclick="startKanjiStudy()">${isDue(x.k)?'revisar agora':'continuar estudo'} →</button></div><div class="ka-mastery"><span class="eyebrow">domínio</span><strong>${m.overall}%</strong><div class="ka-ring" style="--p:${m.overall}"></div><ul><li><span>significado</span><b>${masteryState(m.meaning)}</b></li><li><span>leitura</span><b>${masteryState(m.reading)}</b></li><li><span>contraste</span><b>${masteryState(m.contrast)}</b></li><li><span>escrita</span><b>${masteryState(m.writing)}</b></li></ul></div></div>`}
function renderKanjiFocus(){const x=kanjiData[currentKanji],el=document.getElementById('kanjiFocus');if(el)el.innerHTML=kanjiFocusMarkup(x)}
function startKanjiStudy(){kanjiStudyStep='meaning';renderKanjiStudy()}
function setKanjiStudyStep(step){kanjiStudyStep=step;renderKanjiStudy()}
function renderKanjiStudy(){
 const host=document.getElementById('kanjiStudyFlow');if(!host)return;const x=kanjiData[currentKanji],m=kanjiMastery(x);
 if(kanjiStudyStep==='overview'){host.innerHTML=`<section class="ka-next"><div><span class="eyebrow">próxima melhor ação</span><h3>${m.reading<40?'Prenda a leitura a uma palavra real.':m.writing<40?'Recupere a forma sem olhar.':'Teste o kanji em contexto.'}</h3><p>O Atlas reduz escolhas: treine primeiro a evidência mais fraca.</p></div><button class="secondary" onclick="startKanjiStudy()">iniciar treino →</button></section>`;return}
 const steps=[['meaning','1 · reconhecer'],['reading','2 · ler'],['contrast','3 · diferenciar'],['writing','4 · escrever'],['context','5 · usar']];
 host.innerHTML=`<section class="ka-study"><div class="ka-stepper">${steps.map(([id,label])=>`<button class="${kanjiStudyStep===id?'active':''}" onclick="setKanjiStudyStep('${id}')">${label}</button>`).join('')}</div><div id="kaStudyBody"></div></section>`;
 const body=document.getElementById('kaStudyBody');
 if(kanjiStudyStep==='meaning')body.innerHTML=`<div class="ka-challenge"><span class="eyebrow">recuperação ativa</span><h3>Qual forma corresponde a “${x.m.toLowerCase()}”?</h3><div class="ka-options">${kmOptions(x.k,kanjiData.map(k=>k.k)).map(k=>`<button onclick="answerKanjiMeaning('${k}');renderKanjiFocus()"><b>${k}</b></button>`).join('')}</div><div id="kanjiLabFeedback" class="km-feedback">Escolha antes de rever a resposta.</div></div>`;
 else if(kanjiStudyStep==='reading'){const ex=x.ex[0],pool=kanjiData.flatMap(k=>k.ex.map(e=>e[1]));body.innerHTML=`<div class="ka-challenge"><span class="eyebrow">leitura em contexto</span><h3>${ex[0]}</h3><p>Qual leitura pertence a esta palavra?</p><div class="ka-options readings">${kmOptions(ex[1],pool).map(r=>`<button onclick="answerKanjiReading('${String(r).replaceAll("'","\\'")}');renderKanjiFocus()">${r}</button>`).join('')}</div><div id="kanjiLabFeedback" class="km-feedback">${ex[2]}</div></div>`;
 else if(kanjiStudyStep==='contrast'){const meta=kanjiMemoryMeta(x.k),opts=[...new Set([x.k,...(meta.contrast||[])])].slice(0,3);body.innerHTML=`<div class="ka-challenge"><span class="eyebrow">discriminação visual</span><h3>Toque no caractere “${x.m}”.</h3><div class="ka-options">${opts.map(k=>`<button onclick="answerKanjiContrast('${k}');renderKanjiFocus()"><b>${k}</b></button>`).join('')}</div><div id="kanjiLabChallenge"></div></div>`;
 else if(kanjiStudyStep==='writing')body.innerHTML=`<div class="ka-writing"><div><span class="eyebrow">memória motora</span><h3>Escreva ${x.k} sem olhar.</h3><p>Comece com guia e retire a pista quando estiver pronto.</p><div class="user-actions"><button class="secondary" id="toggleGuide">ocultar guia</button><button class="secondary" id="clearCanvas">limpar</button></div></div><div class="trace-box"><div id="ghostKanji" class="ghost-kanji">${x.k}</div><canvas id="drawCanvas"></canvas></div></div>`;
 else body.innerHTML=`<div class="ka-challenge"><span class="eyebrow">uso real</span><h3>${x.ex[1]?.[0]||x.ex[0][0]}</h3><p>${x.ex[1]?.[1]||x.ex[0][1]} · ${x.ex[1]?.[2]||x.ex[0][2]}</p><button class="secondary" onclick="speak('${(x.ex[1]?.[1]||x.ex[0][1]).replaceAll("'","\\'")}')">▶ ouvir no contexto</button><div class="ka-finish"><button class="primary" onclick="gradeKanji('${x.k}','good');kanjiStudyStep='overview';renderKanjiAtlas()">concluir sessão →</button></div></div>`;
 if(kanjiStudyStep==='writing'&&typeof ensureDrawingCanvases==='function')setTimeout(()=>ensureDrawingCanvases(),0);
}
function renderKanjiContext(){const x=kanjiData[currentKanji],meta=kanjiMemoryMeta(x.k),host=document.getElementById('kanjiContext');if(!host)return;host.innerHTML=`<section class="ka-context"><div><span class="eyebrow">palavras reais</span><h3>Encontre ${x.k} no mundo.</h3><div class="ka-examples">${x.ex.map(e=>`<article><b>${e[0]}</b><span>${e[1]} · ${e[2]}</span><button onclick="speak('${e[1].replaceAll("'","\\'")}')">▶</button></article>`).join('')}</div></div><aside><span class="eyebrow">anatomia & memória</span><h3>${(meta.parts||[]).join(' + ')||x.k}</h3><p>${meta.cue||x.story}</p><blockquote>${meta.scene||x.story}</blockquote></aside></section>`}
function renderKanjiAtlas(){ensureKanjiAtlas();renderKanjiFocus();renderKanjiStudy();renderKanjiContext();renderKanjiList(activeFilter,document.getElementById('kanjiSearch')?.value||'')}
function selectKanji(i){currentKanji=i;kanjiStudyStep='overview';renderKanjiAtlas()}
function speak(text){if(!('speechSynthesis'in window)){toast('Áudio indisponível neste navegador');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.82;const jp=speechSynthesis.getVoices().find(v=>v.lang?.toLowerCase().startsWith('ja'));if(jp)u.voice=jp;speechSynthesis.speak(u)}
function gradeKanji(k,g,quiet=false){const r=gradeReview('kanji',k,g);state.reviews[k]={...r,m:reviewMastery('kanji',k)};if(!quiet)state.xp+=g==='hard'?3:g==='good'?8:12;save();renderKanjiList(activeFilter,document.getElementById('kanjiSearch')?.value||'');if(!quiet)toast('Revisão agendada • +'+(g==='hard'?3:g==='good'?8:12)+' XP')}

// Explicit global exports for classic lazy-loaded scripts.
Object.assign(window,{ensureKanjiAtlas,renderKanjiAtlas,renderKanjiList,selectKanji,toggleKanjiLibrary,startKanjiStudy,setKanjiStudyStep,speak,gradeKanji});
