const FUNCTIONAL_MASTERY_META=[['repair','Reparar','manter a interação quando algo quebra'],['confirm','Confirmar','checar horário, condição e entendimento'],['explain','Explicar','dar contexto, causa e motivo'],['negotiate','Negociar','propor alternativa, restrição ou decisão'],['summarize','Resumir','devolver o ponto principal e próximo passo']];
function pc(a,i,l,v,n,w){return `<article class="progress-evidence" ${a}="${i}"><span>${l}</span><b>${v}</b><small>${n}</small><i><em data-mon-width="${w}%"></em></i></article>`}
function renderFunctionalMastery(){const g=document.getElementById('progressEvidenceGrid');if(!g)return;g.querySelectorAll('[data-functional-mastery]').forEach(x=>x.remove());g.insertAdjacentHTML('beforeend',FUNCTIONAL_MASTERY_META.map(([i,n,d])=>{const x=state.functionalMastery?.[i],s=Number(x?.score||0),a=Number(x?.attempts||0);return pc('data-functional-mastery',i,'Função · '+n,a?s+'%':'—',d,a?s:0)}).join(''))}
const renderProgressHubBase=renderProgressHub;renderProgressHub=function(){renderProgressHubBase();renderFunctionalMastery()};
function renderLearningEvidence(){const g=document.getElementById('progressEvidenceGrid');if(!g)return;g.querySelectorAll('[data-learning-evidence]').forEach(x=>x.remove());if(typeof learningMetricsSnapshot!=='function')return;const s=learningMetricsSnapshot(state),st={empty:'sem dados',early:'amostra inicial',stale:'dados antigos',ready:'evidência suficiente'};g.insertAdjacentHTML('beforeend',s.metrics.map(x=>pc('data-learning-evidence',x.id,'Métrica · '+x.label,x.value===null?'—':x.value+(x.unit==='%'?'%':''),x.samples+' obs · '+(st[x.status]||x.status),x.unit==='%'?(x.value||0):Math.min(100,x.samples*10))).join(''))}
const renderProgressHubFunctional=renderProgressHub;renderProgressHub=function(){renderProgressHubFunctional();renderLearningEvidence()};
function validationDeltaText(m,l=false){const t=m?.trend;if(!t||t.status!=='directional'||t.delta===null)return 'sem tendência';const g=l?t.delta<0:t.delta>0,b=l?t.delta>0:t.delta<0,a=t.delta>0?'↑':t.delta<0?'↓':'→';return `${a} ${Math.abs(t.delta)} pp · ${g?'melhorando':b?'piorando':'estável'}`}
function renderLearningValidation(){const g=document.getElementById('progressEvidenceGrid');if(!g||typeof learningValidationReport!=='function')return;g.querySelectorAll('[data-learning-validation]').forEach(x=>x.remove());const r=learningValidationReport(state),c=[...r.retention.map(x=>({id:'ret-'+x.id,label:'Retenção '+x.label,value:x.value,samples:x.samples,note:x.status})),{id:'hints',label:'Pistas',value:r.hintDependence.value,samples:r.hintDependence.samples,note:validationDeltaText(r.hintDependence,true)},{id:'transfer-trend',label:'Transferência',value:r.transfer.value,samples:r.transfer.samples,note:validationDeltaText(r.transfer)},{id:'autonomy-trend',label:'Autonomia',value:r.autonomy.value,samples:r.autonomy.samples,note:validationDeltaText(r.autonomy)},{id:'recurrent-errors',label:'Erros',value:r.recurrentErrors.value,samples:r.recurrentErrors.samples,note:validationDeltaText(r.recurrentErrors,true)}];g.insertAdjacentHTML('beforeend',c.map(x=>pc('data-learning-validation',x.id,'Validação · '+x.label,x.value===null?'—':x.value+'%',x.samples+' observações · '+x.note,x.value||0)).join(''))}
const renderProgressHubMetrics=renderProgressHub;renderProgressHub=function(){renderProgressHubMetrics();renderLearningValidation()};
function renderReadingMastery(){const g=document.getElementById('progressEvidenceGrid');if(!g)return;g.querySelectorAll('[data-reading-mastery]').forEach(x=>x.remove());const c=state.masteryEvidence?.['reading:global']?.recall,a=Number(c?.attempts||0),s=Number(c?.score||0),t=a<3?'calibrando':s>=80?'sem apoio':s>=55?'furigana':'romaji';g.insertAdjacentHTML('beforeend',pc('data-reading-mastery','global','Leitura · autonomia',a?s+'%':'—',a+' leituras sem pista · apoio atual: '+t,a?s:0))}
const renderProgressHubReading=renderProgressHub;renderProgressHub=function(){renderProgressHubReading();renderReadingMastery()};
