// MON profile UI — loaded with the account boundary.
function userAreaMarkup(){
 return '<div class="user-shell"><section class="user-auth-gate" id="userAuthGate"><span class="eyebrow">Conta MON · 門</span><h2>Acesse sua conta</h2><p>Entre com e-mail e senha ou crie uma conta nova para sincronizar seu progresso.</p><div class="user-data-note" id="userCloudPanel"></div></section><div id="userProfileShell" class="user-profile-shell" hidden><div class="user-hero"><div class="user-identity"><div class="user-avatar" id="userAvatar">門</div><div><span class="eyebrow">Minha área · 私</span><h2 id="userNameHero">Estudante MON</h2><p id="userPlanHero">Seu progresso e suas preferências neste dispositivo.</p></div></div><span class="user-local-badge" id="userAccountBadge">perfil local</span></div><div class="user-grid"><section class="user-card"><h3>Seu aprendizado</h3><p>Uma leitura rápida do seu momento, sem transformar estudo em painel de vaidade.</p><div class="user-stats"><div class="user-stat"><span>nível</span><b id="userLevel">N5</b></div><div class="user-stat"><span>sequência</span><b id="userStreak">1 dia</b></div><div class="user-stat"><span>XP</span><b id="userXp">0</b></div></div><div class="user-progress-line"><i id="userJourneyBar"></i></div><div class="user-data-note" id="userJourneyText"></div><div class="user-actions"><button class="user-secondary" onclick="go(\'progress\')">ver progresso</button><button class="user-secondary" onclick="go(\'journey\')">abrir jornada</button></div></section><section class="user-card"><h3>Perfil e rotina</h3><p>Preferências simples para o MON adaptar a experiência sem exigir uma conta.</p><label class="user-field"><span>Como quer ser chamado</span><input id="userNameInput" maxlength="32" autocomplete="nickname"></label><label class="user-field"><span>Meta diária</span><select id="userGoalInput"><option value="10">10 min · leve</option><option value="20">20 min · consistente</option><option value="30">30 min · intenso</option></select></label><label class="user-field"><span>Ritmo preferido</span><select id="userModeInput"><option value="equilibrado">Equilibrado</option><option value="revisao">Mais revisão</option><option value="desafio">Mais desafio</option></select></label><label class="user-field"><span>Ajuda de leitura</span><select id="userRomajiInput"><option value="auto">Adaptativa · diminui com o progresso</option><option value="show">Sempre mostrar romaji</option><option value="hide">Ocultar romaji</option></select></label><div class="user-actions"><button class="user-save" onclick="saveUserArea()">salvar preferências</button><button class="user-secondary" onclick="exportMonBackup()">exportar backup</button></div><div class="user-data-note" id="userAccountNote">Seu aprendizado continua salvo localmente neste navegador.</div></section></div></div></div>';
}
function setMonUserAuthState(connected){const profile=document.getElementById('userProfileShell'),gate=document.getElementById('userAuthGate');if(profile)profile.hidden=!connected;if(gate)gate.classList.toggle('signed-out',!connected)}
function ensureUserArea(){let view=document.getElementById('user');if(view)return view;view=document.createElement('section');view.id='user';view.className='view';view.innerHTML=userAreaMarkup();document.querySelector('.content')?.appendChild(view);return view}
function renderUserArea(){
 ensureUserArea();const profile=loadLocalProfile(),p=currentPlan(),stage=JOURNEY_STAGES[journeyStageIndex()],pct=Math.round(journeyStageProgress()*100);
 const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set('userNameHero',profile.name);set('userLevel',(p.displayLevel||p.level)+' · dia '+p.localDay+'/'+p.total);set('userStreak',(state.streak||0)+' '+((state.streak||0)===1?'dia':'dias'));set('userXp',state.xp||0);set('userJourneyText',stage.name+' · '+stage.title+' · '+pct+'% da etapa');const bar=document.getElementById('userJourneyBar');if(bar)bar.style.width=pct+'%';const name=document.getElementById('userNameInput'),goal=document.getElementById('userGoalInput'),mode=document.getElementById('userModeInput');if(name)name.value=profile.name;if(goal)goal.value=String(profile.dailyGoal);if(mode)mode.value=profile.studyMode;const romaji=document.getElementById('userRomajiInput');if(romaji)romaji.value=state.romajiMode||'auto';const avatar=document.getElementById('userAvatar');if(avatar)avatar.textContent=(profile.name.trim()[0]||'門').toUpperCase();const account=loadMonAccount(),badge=document.getElementById('userAccountBadge'),note=document.getElementById('userAccountNote');if(badge)badge.textContent=monAccountStatus()==='connected'?'conta conectada':'perfil local';if(note)note.textContent=typeof monCloudConfigured==='function'&&monCloudConfigured()?'Conta MON disponível. Crie sua conta ou entre com e-mail e senha para sincronizar entre dispositivos.':'Seu progresso fica neste navegador. Exporte um backup antes de trocar de dispositivo.';renderCloudAccountPanel();renderOfflinePanel();
}
function saveUserArea(){const name=(document.getElementById('userNameInput')?.value||'Estudante MON').trim().slice(0,32)||'Estudante MON',dailyGoal=Number(document.getElementById('userGoalInput')?.value||20),studyMode=document.getElementById('userModeInput')?.value||'equilibrado',romajiMode=document.getElementById('userRomajiInput')?.value||'auto';try{saveLocalProfile({name,dailyGoal,studyMode});state.romajiMode=['auto','show','hide'].includes(romajiMode)?romajiMode:'auto';save();renderUserArea();toast('Preferências salvas neste dispositivo')}catch{toast('Não foi possível salvar suas preferências. Tente novamente.')}}



